### ISSUE TITLE
Organizar acta de constitución del proyecto

### ISSUE THREAD

**Issue by Tecnojack** [SarayGal/Unac-Virtual-Tracking#1]
- Reunir información por cada uno de los responsables de las diferentes actividades par el desarrollo del acta
- Adecuar el formato de entrega
- Dar coherencia al documento

**Comment by Nix0n98** [comment]
https://docs.google.com/document/d/1dGiMJyi2EEK8Cocts7f3RibZpdrZ8YrJsxfVBnnrgb4/edit?usp=sharing
