### ISSUE TITLE
Director del proyecto

### ISSUE THREAD

**Issue by Rosmira** [SarayGal/Unac-Virtual-Tracking#10]

**Comment by Rosmira** [comment]
DIRECTOR DEL PROYECTO 

JOSE MILLER CASIERRA ÁLVAREZ
Director /Gerente del proyecto
Estudiante de ingeniería de sistemas,Corporación Universitaria Adventista.

**Comment by SarayGal** [comment]
Puedes agregar...
Su equipo, compuesto por X desarrolladores, cuantos de front y back, será un soporte matricial de la Empresa. También coordinará todos los requisitos de recursos a través del jefe del proyecto, XX Profe Walter. Cualquier financiamiento adicional debe solicitarse a través del Patrocinador del Proyecto, Decano. El gerente proporcionará actualizaciones semanales a los miembros del equipo del Proyecto.
