### ISSUE TITLE
Mockups 

### ISSUE THREAD

**Issue by SarayGal** [SarayGal/Unac-Virtual-Tracking#11]
Idealizando como sería el software

**Comment by JesielPalacios** [comment]
La página de registro idealizada fue la siguiente:
![Sign Up](https://user-images.githubusercontent.com/50146090/111240016-65a1fb80-85c8-11eb-97ed-9cf9869f65c3.png)

La página de ingreso (login )idealizada fue la siguiente:
![Sign In](https://user-images.githubusercontent.com/50146090/111240030-6b97dc80-85c8-11eb-8da8-ddf678955d39.png)

**Comment by Tecnojack** [comment]
![Calendar](https://user-images.githubusercontent.com/51295285/111240364-14ded280-85c9-11eb-963b-c7e1655cd1ac.png)
![dashboard 1](https://user-images.githubusercontent.com/51295285/111240367-160fff80-85c9-11eb-8530-b8de26ca829d.jpg)
![Payments](https://user-images.githubusercontent.com/51295285/111240369-160fff80-85c9-11eb-844b-251be9401926.png)
![Schedule](https://user-images.githubusercontent.com/51295285/111240370-16a89600-85c9-11eb-8644-f70b0131e808.png)

**Comment by SarayGal** [comment]
Excelente Jack

**Comment by JesielPalacios** [comment]
Hola profe, una pregunta, donde hago yo para ver por donde usted nos deja
las observaciones de cada una de las asignaciones hechas y que ya se han
completado y todo eso?, es que yo a las malas solo se subir código en
Github y cositas así jejej😁😅
