### ISSUE TITLE
Requisitos alto nivel

### ISSUE THREAD

**Issue by SarayGal** [SarayGal/Unac-Virtual-Tracking#13]

**Comment by SarayGal** [comment]
Por favor agregar los requisitos de alto nivel

**Comment by Nix0n98** [comment]
Requisitos Funcionales
Los requisitos pueden ser especificados inicialmente de una manera informal: 
Identificador: RF 001
Descripción del requisito
Sujeto – Verbo – Objeto Directo
RF1: El sistema debe hacer un seguimiento de los estudiantes
RF2: El sistema debe permitir el registro  de los estudiantes y docentes perteneciente al proyecto integrador. 
RF3: El sistema debe  modificar los datos personales de estudiantes y docentes.
RF4: El sistema debe permitir que los estudiantes hagan autoevaluaciones
RF5: El sistema debe permitir buscar información o documentos correspondientes a su proyecto. 
RF6: El sistema debe permitir subir documentos. 
RF7: El sistema debe permitir el registro de materias por estudiante del proyecto integrador.
RF8: El sistema debe tener un login.  
RF9: El sistema debe permitir la gestión de roles
RF10: El sistema debe adicionar los datos personales del cliente.
RF11: El Sistema debe permitir que dos o más periodos contables estén abiertos al mismo tiempo.

Requisito no Funcional
RNF 1: El sistema debe funcionar continuamente (24/7)
RNF2: El sistema debe tener un almacenamiento propio para tener en la plataforma los archivos. 
RNF 3: El sistema debe poder ofrecer el servicio a muchos usuarios de manera concurrente.

**Comment by MoisesResabala** [comment]
Hola profe también trabaje en esto
