### ISSUE TITLE
Calendario de  los hitos

### ISSUE THREAD

**Issue by javiersandoval04** [SarayGal/Unac-Virtual-Tracking#17]
Hito del proyecto 

·           Acta del proyecto | 17/03/2021
·           Adecuación del ambiente de desarrollo | 22/03/2021
·           Inicio del proyecto | 29/03/2021
·           Reunión de planificación del Sprint (1) | 31/03/2021
·           Desarrollo del Sprint (1) | 04/04/2021
·           Revisión del Sprint (1) | 12/04/2021
·           Retrospectiva del Sprint (1) | 14/04/2021
·           Reunión de planificación del Sprint (2) | 18/04/2021
·           Desarrollo del Sprint (2) | 25/04/2021
·           Revisión del Sprint (2) | 03/05/2021
·           Retrospectiva del Sprint (2) | 10/05/2021
·           Cierre del Proyecto | 31/05/2021

**Comment by SarayGal** [comment]
Buen día Javier! 

Agrega también por favor las otras actividades que desarrollaremos en el curso. Esta información está en la diapositivas del curso de la primera semana.

**Comment by SarayGal** [comment]
Por favor agrega las actividades del comentario anterior

**Comment by javiersandoval04** [comment]
Hito del proyecto | Fecha objetivo
-- | --
·         Acta del proyecto | 17/03/2021
·         Adecuación del ambiente de desarrollo | 22/03/2021
·         Inicio del proyecto | 29/03/2021
·         Ejecución y gestión del conocimiento Sprint (1) | 29/03/2021
·         Reunión de planificación del Sprint (1) | 31/03/2021
·         Desarrollo del Sprint (1) | 04/04/2021
·         Ejecución y gestión del conocimiento Sprint (1) | 05/04/2021
·         Revisión del Sprint (1) | 12/04/2021
·         Ejecución y gestión del conocimiento Sprint (1) | 12/04/2021
·         Retrospectiva del Sprint (1) | 14/04/2021
·         Reunión de planificación del Sprint (2) | 18/04/2021
·         Ejecución y gestión del conocimiento Sprint (2) | 19/04/2021
·         Desarrollo del Sprint (2) | 25/04/2021
·         Ejecución y gestión del conocimiento Sprint (2) | 26/04/2021
·         Revisión del Sprint (2) | 03/05/2021
·         Ejecución y gestión del conocimiento Sprint (2) | 03/05/2021
·         Retrospectiva del Sprint (2) | 10/05/2021
·         Riesgos del proyecto | 24/0572021
·         Cierre del Proyecto | 31/05/2021
