### ISSUE TITLE
Identificar a las partes interesadas

### ISSUE THREAD

**Issue by Jose714** [SarayGal/Unac-Virtual-Tracking#20]
En esta sección se debe discutir la metodología que utilizará el equipo del proyecto para identificar a las partes interesadas y cómo se definen las partes interesadas.  Es imperativo que todas las partes interesadas sean identificadas independientemente de lo importantes o menores que sean.  Esto se debe a que se clasificarán después de que se identifiquen.  Si se omite a las partes interesadas, existe la probabilidad de que puedan hacerse evidentes en algún momento durante el ciclo de vida del proyecto e introducir retrasos u otros obstáculos para el éxito del proyecto.  Se debe dedicar un gran cuidado y esfuerzo a este paso de la Estrategia de Gestión de Las Partes Interesadas.

**Comment by MoisesResabala** [comment]
[Identificar parte Interesadas.docx](https://github.com/SarayGal/Unac-Virtual-Tracking/files/6178460/Identificar.parte.Interesadas.docx)

Aqui esta mi aporte a las partes interesada falta agregar los criterios alguien de mis otros tres compañeros asignados que se pueda hacer cargo de esa parte  y mejorar mas esta sesión

**Comment by danduke99** [comment]
> [Identificar parte Interesadas.docx](https://github.com/SarayGal/Unac-Virtual-Tracking/files/6178460/Identificar.parte.Interesadas.docx)
> 
> Aqui esta mi aporte a las partes interesada falta agregar los criterios alguien de mis otros tres compañeros asignados que se pueda hacer cargo de esa parte y mejorar mas esta sesión

Voy a indentificar todos los stakeholders

**Comment by JesielPalacios** [comment]
> > [Identificar parte Interesadas.docx](https://github.com/SarayGal/Unac-Virtual-Tracking/files/6178460/Identificar.parte.Interesadas.docx)
> > Aqui esta mi aporte a las partes interesada falta agregar los criterios alguien de mis otros tres compañeros asignados que se pueda hacer cargo de esa parte y mejorar mas esta sesión
> 
> Voy a indentificar todos los stakeholders

Aquí está una posible complementación a la identificación de los interesados y Stakeholders, quedo pendiente a comentarios y concejos de mejora.

[Identificar a las partes interesadas y Stakeholders.docx](https://github.com/SarayGal/Unac-Virtual-Tracking/files/6184293/Identificar.a.las.partes.interesadas.y.Stakeholders.docx)

**Comment by MoisesResabala** [comment]
Ya subí la mejoras en link que dejo el gerente Miuller en el grupo de WhatsApp cualquier cambio que desean realizar lo aplican allá  directamente.

**Comment by MoisesResabala** [comment]
Esta actividad tuvo un tiempo estimado de 55 minutos.

**Comment by JesielPalacios** [comment]
En esta actividad se tomó al rededor de unos 30 minutos.

**Comment by danduke99** [comment]
Tiempo real: 1.5 horas
