### ISSUE TITLE
Principales partes interesadas

### ISSUE THREAD

**Issue by Jose714** [SarayGal/Unac-Virtual-Tracking#21]
Esto identifica el sub-conjunto de partes interesadas que han sido identificadas como partes interesadas clave y el razonamiento para determinar que son partes interesadas clave.  Las partes interesadas clave son a menudo aquellas que potencialmente tienen más influencia sobre un proyecto o aquellos que pueden ser los más afectados por el proyecto.  También pueden ser partes interesadas que se resisten al cambio representado por el proyecto.  Estas partes interesadas clave pueden requerir más comunicación y gestión a lo largo del ciclo de vida del proyecto y es importante identificarlas para que busquen sus comentarios sobre su nivel deseado de participación y comunicación.

**Comment by Rosmira** [comment]
Las partes Interesadas del proyecto 

Parte Interna 
Gerente del proyecto encargado (Jose Miller)
Estudiantes de 9 semestre, Materia Gerencia de proyectos (equipo de trabajo del proyecto)
Profesora de Gerencia de proyectos (Saray)
Decanos de las facultades de la Universidad
Profesores de todas las facultades de la Universidad
Equipo administrativo de la Universidad
Rector de la Universidad 
Estudiantes de todas las facultades de la Universidad

Parte externa 
(clientes, usuarios, proveedores ....)

**Comment by Rosmira** [comment]
Compañeros de proyecto @Jose714 @javiersandoval04 @JoseBaldovino1014 esta es la parte que investigue y pude identificar de los interesados para el proyecto me ayudan revisando si estoy en lo correcto que debo corregir por favor o si estoy equivocada en esta parte 
en donde dice parte externa es para continuar colocando mas interesados quiero saber si esa es la idea de este punto para continuar  muchas gracias

**Comment by JoseBaldovino1014** [comment]
Excelente, mañana temprano reviso y terminamos de hacerlo.

**Comment by JoseBaldovino1014** [comment]
-	DIRECTOR DEL PROYECTO: CASIERRA ALVAREZ JOSE MILLER
-	ORGANIZACION: CORPORACIÓN UNIVERSITARIA ADVENTISTA 
-	CLIENTES: GALEANO OSPINO SARAY - DOCENTE
-	EQUIPO DE TRABAJO: DUFFIS DUKE DEELAN DANIEL, FUENTES QUITIAN JENNYFER JACKELINE, OCHOA PERDOMO NIXON JAVIER, PALACIOS CORDOBA JACKSON ISAAC, PALACIOS SALINAS JESIEL OBED, PEREZ CADENA ROSMIRA, RESABALA MOREIRA MOISES ISRRAEL, SANDOVAL APARICIO FRANCISCO JAVIER, JOSÉ DAVID BALDOVINO ROJAS.
-	COMUNIDAD:
-	INVERSIONISTAS:

**Comment by Rosmira** [comment]
exacto asi es @JoseBaldovino1014 gracias

**Comment by JoseBaldovino1014** [comment]
Tiempo que realicé esto. 50 Minutos

**Comment by Rosmira** [comment]
TIEMPO ESTIMADO QUE REALICE ESTA ACTIVIDAD  1 HORA

**Comment by JoseBaldovino1014** [comment]
EL tiempo estimado en el que pensé que iba demorar realizando esta actividad fue de 1 HORA, pero realmente solo demoré 50 MINUTOS
