### ISSUE TITLE
Analisis de las partes interesadas

### ISSUE THREAD

**Issue by Jose714** [SarayGal/Unac-Virtual-Tracking#22]
En esta sección se describe cómo el equipo del proyecto analizará su lista de partes interesadas identificadas.  Esta discusión debe incluir cómo las partes interesadas serán categorizadas o agrupadas, así como el nivel de impacto que puedan tener basado en su poder, influencia e participación en el proyecto.  Hay varias herramientas y técnicas que se pueden utilizar para ayudar a cuantificar a las partes interesadas.  En esta sección también debe incluirse una descripción de estas herramientas y técnicas.

**Comment by Nix0n98** [comment]
Objetivos del análisis: 
1. Categorizar o agrupar las partes interesadas. 
2. Nivel de impacto en el proyecto. 
3. Herramientas y técnicas de cuantificación a las partes interesadas.

**Comment by Nix0n98** [comment]
Tomando en cuenta otro Issue de mis compañeros, las partes interesadas están categorizadas o agrupadas de la siguiente manera: 

**DIRECTOR DEL PROYECTO:** CASIERRA ALVAREZ JOSE MILLER
**ORGANIZACION:** CORPORACIÓN UNIVERSITARIA ADVENTISTA
**CLIENTES:** GALEANO OSPINO SARAY - DOCENTE
**EQUIPO DE TRABAJO:** DUFFIS DUKE DEELAN DANIEL, FUENTES QUITIAN JENNYFER JACKELINE, OCHOA PERDOMO NIXON JAVIER, PALACIOS CORDOBA JACKSON ISAAC, PALACIOS SALINAS JESIEL OBED, PEREZ CADENA ROSMIRA, RESABALA MOREIRA MOISES ISRRAEL, SANDOVAL APARICIO FRANCISCO JAVIER, JOSÉ DAVID BALDOVINO ROJAS.
**COMUNIDAD:** DOCENTES, ESTUDIANTES Y UNIVERSIDAD.

**Comment by Nix0n98** [comment]
Nivel de impacto:


Clave | Skateholders | Nombres | Poder (1-5) | Interés (1-5)
-- | -- | -- | -- | --
A | Director de Proyecto | CASIERRA ALVAREZ JOSE MILLER | 5 | 5
B | Organización | CORPORACIÓN UNIVERSITARIA ADVENTISTA | 5 | 5
C | Clientes | GALEANO OSPINO SARAY - DOCENTE | 4 | 4
D | Equipo de trabajo | DUFFIS DUKE DEELAN DANIEL, FUENTES QUITIAN JENNYFER JACKELINE, OCHOA PERDOMO NIXON JAVIER, PALACIOS CORDOBA JACKSON ISAAC, PALACIOS SALINAS JESIEL OBED, PEREZ CADENA ROSMIRA, RESABALA MOREIRA MOISES ISRRAEL, SANDOVAL APARICIO FRANCISCO JAVIER, JOSÉ DAVID BALDOVINO ROJAS. | 3 | 4
E | Comunidad | DOCENTES, ESTUDIANTES Y UNIVERSIDAD. | 2 | 3

**Comment by Nix0n98** [comment]
[Análisis Skateholders.docx](https://github.com/SarayGal/Unac-Virtual-Tracking/files/6186637/Analisis.Skateholders.docx)
![Captura de pantalla 2021-03-22 a las 22 05 49](https://user-images.githubusercontent.com/80726964/112086899-0bbaac00-8b5b-11eb-999a-db104d7ec93b.png)

**Comment by Nix0n98** [comment]
Tiempo en que realicé esto. 40 minutos

**Comment by Nix0n98** [comment]
Tiempo estimado: 1 hora.

**Comment by Tecnojack** [comment]
![TECNOJACK (20)](https://user-images.githubusercontent.com/51295285/113537699-0586ef80-959f-11eb-9f4d-12644793b92d.png)


Sobre la base del análisis de poder e intereses y el gráfico anterior, las partes interesadas E, requerirán un mínimo esfuerzo de gestión, ya que residen en el cuadrante inferior izquierdo de la matriz. Las partes interesadas G, en el cuadrante inferior derecho, deben mantenerse informadas mediante una comunicación frecuente sobre el estado y el progreso del proyecto.  Las partes interesadas A, B y C, en el cuadrante superior derecho, son actores clave y deben participar en todos los niveles de planificación de proyectos y gestión del cambio.  Además, deben ser miembros participativos en todas las reuniones de estado del proyecto, revisiones de puertas y reuniones ad hoc según sea necesario.

**Comment by SarayGal** [comment]
No encuentro las Preocupaciones de las partes interesadas, el nivel de participación y la estrategia de gestión basada en el análisis de las partes interesadas.

Además no sé porque se quitaron a las personas responsables de esta actividad.

**Comment by Nix0n98** [comment]
Tiempo total: 2 horas.
