### ISSUE TITLE
Descripción del proyecto

### ISSUE THREAD

**Issue by Tecnojack** [SarayGal/Unac-Virtual-Tracking#4]
- Objetivos
- Criterios de éxito

**Comment by SarayGal** [comment]
Un ejemplo....
La XXXXX tiene como objetivo a corto plazo promocionar su servicio entre todos los sitios de ventas potenciales, ya sean lugares físicos, plataformas en internet u otros y así logrará dar un importante paso para el objetivo principal de mediano plazo que ya es la captura de todos los clientes y como tal el inicio de ventas ya de forma consistente. Evidentemente esto ligado a la mejora constante del servicio, ya sea a la hora de vender, e1<4c d5n la calidad de los productos, entrega, entre otras.
A largo plazo la XXXX tiene como objetivo:
1.	Expandir los productos 
2.	Generar más empleo.

**Comment by MoisesResabala** [comment]
> * Objetivos
> * Criterios de éxito

esto lo realice yo

**Comment by MoisesResabala** [comment]
**Objetivo del proyecto y criterios de éxito:**
Se ha identificado los objetivos que apoyan los hitos de este proyecto y su resultado.
Para lograr el éxito de este proyecto debe cumplirse los siguientes objetivos dentro de las asignaciones propuestas.
•	Desarrollar la metodología de acuerdo con los temas planteados para mostrarle al gerente de proyecto para su aprobación.
•	En listar las tecnologías utilizar en la elaboración del software requerida con la asignación de este proyecto.
•	Asignar las diferentes tareas a los diferentes miembros del equipo para el desarrollo de la solución del proyecto.
•	Lograrla construcción total y parcial del software para la realización de pruebas elijadas por el gerente.
•	Mostrar la solución final a nuestra institución con el fin de retroalimentarnos y mejorar la aplicación web.
