### ISSUE TITLE
D001 Documento arquitectura de la solución

### ISSUE THREAD

**Issue by Jennyfer1997** [SarayGal/Unac-Virtual-Tracking#46]

**Comment by Rosmira** [comment]
![WhatsApp Image 2021-04-12 at 7 17 59 PM](https://user-images.githubusercontent.com/26470460/114478512-05e94100-9bc4-11eb-9569-1665be4771a8.jpeg)

**Comment by JoseBaldovino1014** [comment]
![Diagrama de clases](https://user-images.githubusercontent.com/32313570/114479134-78a6ec00-9bc5-11eb-9717-3d90c41011ad.jpeg)

**Comment by JoseBaldovino1014** [comment]
![Diagrama](https://user-images.githubusercontent.com/32313570/114479187-9aa06e80-9bc5-11eb-95b6-6bea2e698ff9.jpeg)

**Comment by SarayGal** [comment]
@Jose714 Como hacer un diagrama de clases.

**Comment by Jose714** [comment]
Puedes guiarte de aqui, ahi explican como hacerlo https://youtu.be/NM7i89tF3Ks

**Comment by JoseBaldovino1014** [comment]
Diagrama de Clases en Lucidchart : https://lucid.app/lucidchart/802d3406-975c-4a91-a7a9-947f5d812811/edit?beaconFlowId=4B1002602FDC14C7&page=HWEp-vi-RSFO#

**Comment by JoseBaldovino1014** [comment]
Diagrama de Clases en Lucidchart: https://lucid.app/lucidchart/invitations/accept/inv_e37ff96f-3173-4dd6-bd0b-f19d7850e934?viewport_loc=26%2C-41%2C1952%2C762%2CHWEp-vi-RSFO

**Comment by SarayGal** [comment]
4 hr

**Comment by JoseBaldovino1014** [comment]
![Diagrama de Clases - Clase UML](https://user-images.githubusercontent.com/32313570/115319437-730d5100-a145-11eb-82ec-a2bd242bd128.jpeg)

**Comment by JoseBaldovino1014** [comment]
Tiempo estimado: 8H

**Comment by SarayGal** [comment]
[Diagrama de clases.pptx](https://github.com/SarayGal/Unac-Virtual-Tracking/files/6339951/Diagrama.de.clases.pptx)

**Comment by Rosmira** [comment]
necesito ayuda de definición de las clases en el diagrama

**Comment by Tecnojack** [comment]
Yo te ayudo, Rosmira!

**Comment by Rosmira** [comment]
@Tecnojack gracias por su colaboracion 
![WhatsApp Image 2021-04-19 at 3 34 59 PM](https://user-images.githubusercontent.com/26470460/115328692-a4424d00-a156-11eb-84cc-8060d06177cb.jpeg)

**Comment by Rosmira** [comment]
actualizacion del diagrama de clase 
https://lucid.app/lucidchart/802d3406-975c-4a91-a7a9-947f5d812811/edit?shared=true&page=HWEp-vi-RSFO#
tiempo estimado 1 hora

**Comment by JoseBaldovino1014** [comment]
Actualización Diagrama de Clases
![Diagrama de Clases - Clase UML (1)](https://user-images.githubusercontent.com/32313570/115549938-df37a400-a26e-11eb-9ec8-8508493578bc.jpeg)

**Comment by Rosmira** [comment]
Tiempo estimado total 10 horas
