### ISSUE TITLE
T007 Crear pantalla de registro

### ISSUE THREAD

**Issue by Jose714** [SarayGal/Unac-Virtual-Tracking#48]

**Comment by SarayGal** [comment]
Estimación: 2hr

**Comment by Nix0n98** [comment]
Tiempo de realización: 1h 37 minutos

**Comment by Nix0n98** [comment]
Aquí podrán encontrar el código del proyecto: https://drive.google.com/file/d/1sGg--qZai_PjwMH5OYE6sdtJvg-unuY6/view?usp=sharing
