### ISSUE TITLE
Requisitos del acta de constitución

### ISSUE THREAD

**Issue by Tecnojack** [SarayGal/Unac-Virtual-Tracking#5]

**Comment by SarayGal** [comment]
Te recomiento redactar los requisitos de esta forma


Este proyecto debe cumplir con la siguiente lista de requisitos para lograr el éxito.
La solución debe implementarse sin interrumpir las operaciones.

Se necesita desarrollar una web con una serie de puntos valiosos para el control de cada uno tipo oficina virtual, y se pueda ver el desarrollo de cada uno en su avance, tienda virtual más desarrollada y precisa con una agradable vista y fácil de manejar.

•	Tienda: Aquí queremos mejorar la vista de los productos y tener varios filtros de búsqueda sólo se tiene una que es por código de producto, además cada rango tiene un descuento especial por rango obtenido, que va desde el 10% de descuento al 40%, deben elegir si quieres agregar el envío individual y tener control de inventario, también especificar algunos productos que no tiene descuento por ser promociones.
•	Facturas: Guardar todas las facturas de compras realizadas, que si soy coordinadora o directora pueda ver las facturas de mi red y que puedan imprimirlas o exportar a pdf, no pueden modificar facturas solo verlas.
•	Carrito de compra: En esta parte estarán los productos que quiero comprar y tengo dos opciones, finalizar la compra o dejar los productos en carrito, aquí se especifica el total, el descuento que se hace, y cuanto tiene que pagar en total, también mostrar en cantidades de dinero cuál es el descuento de cada producto, poder modificar las cantidades que deseo o eliminar productos que no deseo en mi factura.
•	Reporte: aquí se verá reflejado los reportes de ventas por campaña si deseo revisar campañas antiguas se puede y la actual con sus comisiones, abonos dados, ganancias, premios y cartera atrasada. Se especifica la comisión por volumen de venta dada.
•	Documentación: aquí se entregan todos los documentos requeridos para las diferentes partes en premios o solicitudes.
