### ISSUE TITLE
T004 recuperar usuario y contraseña backend

### ISSUE THREAD

**Issue by Jose714** [SarayGal/Unac-Virtual-Tracking#50]

**Comment by SarayGal** [comment]
Estimación: 2hr

**Comment by MoisesResabala** [comment]
Me tome un tiempo para este spring  de 18 horas

**Comment by MoisesResabala** [comment]
[Como recuperar Usuario y contraseña- Moises Resabala.pdf](https://github.com/SarayGal/Unac-Virtual-Tracking/files/6340310/Como.recuperar.Usuario.y.contrasena-.Moises.Resabala.pdf)
Documento explicativo
