### ISSUE TITLE
T003 Registro estudiantes y docentes

### ISSUE THREAD

**Issue by Jose714** [SarayGal/Unac-Virtual-Tracking#51]

**Comment by SarayGal** [comment]
Pantallas de registro de estudiante y docente

**Comment by SarayGal** [comment]
Estimación:  1 hr

**Comment by JesielPalacios** [comment]
Tiempo estimado: 2 Horas.
Tiempo real: 3 Horas.

**Comment by JesielPalacios** [comment]
Actualizar por favor la info de la API para poder consumirla y editarla, gracias por su atención.

**Comment by JesielPalacios** [comment]
Me aparece esto de la rama main:
![image](https://user-images.githubusercontent.com/50146090/116169624-c2fe9180-a6ca-11eb-9b93-572ff3c53be2.png)

![image](https://user-images.githubusercontent.com/50146090/116169639-cbef6300-a6ca-11eb-98b8-65391b43655d.png)
