### ISSUE TITLE
T006 Modelo de base de datos ER

### ISSUE THREAD

**Issue by Jennyfer1997** [SarayGal/Unac-Virtual-Tracking#54]

**Comment by SarayGal** [comment]
Estimación: 4hr

**Comment by Jennyfer1997** [comment]
[UVT DATABASE.txt](https://github.com/SarayGal/Unac-Virtual-Tracking/files/6339645/UVT.DATABASE.txt)

**Comment by Jennyfer1997** [comment]
![image](https://user-images.githubusercontent.com/54560496/115327597-d5ba1900-a154-11eb-9909-0deabb610e2b.png)

**Comment by Jennyfer1997** [comment]
Tiempo real: 6 hrs
