### ISSUE TITLE
Declaración preliminar del alcance y Supuestos

### ISSUE THREAD

**Issue by Tecnojack** [SarayGal/Unac-Virtual-Tracking#6]

**Comment by Tecnojack** [comment]
**DECLARACIÓN PRELIMINAR DEL ALCANCE**
Nuestro proyecto incluye una fase de diseño de la arquitectura solución, posteriormente se realizan pruebas a la misma y dependiendo del resultado de estas pruebas, estando lista para la entrega de la plataforma de gestión de proyecto integrador. Para todas las fases del proyecto, el equipo de desarrollo formado en la clase de Gerencia proyectos informáticos, dispondrá del recurso humano, las máquinas, y los diferentes programas que se requieran para el desarrollo de la solución. El proyecto se realizará durante el primer semestre de 2021 y los desarrolladores trabajarán desde sus casas de manera remota y se hará integración a través de un repositorio en Github.

El proyecto será financiado por la corporación universitaria adventista y momentáneamente contamos con que no se realicen las modificaciones a lo que ya pactado. De haber algún cambio o consideración adicional, el equipo debe aprobar esta modificación. Este proyecto deberá finalizar para los últimos días del semestre 2021-1. Se debe realizar las últimas pruebas para el despliegue posterior e implementación de la solución en la corporación universitaria adventista UNAC. Todo esto es posible y cuando se cuente con toda la documentación técnica completada y el software cumple con todos los requisitos establecidos previamente para decidir unilateralmente el equipo de desarrollo y su líder técnico.

**Comment by SarayGal** [comment]
El proyecto XXX  incluirá el diseño, las pruebas y la entrega de un sistema que permita incrementar la parte productiva del sistema como herramienta fundamental para las _Actividades_   mejorado en toda la organización. Todo el personal, los recursos de hardware y software serán administrados por el promotor proyecto. 

Todo el trabajo del proyecto será independiente de las operaciones diarias y en curso y todas las pruebas requeridas se realizarán con el Desarrollador a cargo. Todos los fondos del proyecto serán administrados por el promotor. 

Cualquier financiamiento adicional requiere la aprobación del patrocinador del proyecto. Este proyecto concluirá cuando el informe final se envíe dentro de los 30 días posteriores a la prueba y despliegue de la solución de la página web en toda la organización, toda la documentación técnica se complete y distribuya al personal apropiado, y una lista de consideraciones de seguridad futuras se complete.
