### ISSUE TITLE
Riesgos

### ISSUE THREAD

**Issue by Tecnojack** [SarayGal/Unac-Virtual-Tracking#7]

**Comment by Tecnojack** [comment]
**RIESGOS**
El director del proyecto deberá tener en cuenta algunos riesgos que pueden presentarse durante el desarrollo de este. Asimismo, deberá pensar en una solución eficaz para solucionarlos. algunos de los principales riesgos que pueden presentarse son los siguientes:
•	**El alcance**: Está abierta la posibilidad de que el cliente pida algún otro tipo de funcionalidad y la solución será un poco más extensa, por lo que habrá que realizar más reuniones de seguimiento, modificar los diseños y ejecutar más pruebas, lo que ocasionará modificación en el alcance del proyecto. 
•	**Errores de planeación**: Al trabajar con un equipo cuyos conocimientos no son extensos y por la modalidad virtual en la que estamos, será muy probable que algunos de los lineamientos establecidos no se lleven a cabo de la mejor manera o exactamente como se había previsto inicialmente. Por el entorno no controlado en el que se desarrollará el software, factores como el internet, la capacidad en temas del hardware de las máquinas con los que se trabajará, y el conocimiento de los desarrolladores, podrían influir de manera negativa en el desarrollo del proyecto.
•	**Problemas de comunicación:** Por la modalidad virtual en la que se trabajará el proyecto y por las pocas oportunidades de reunión causadas por la carga académica de cada uno de los desarrolladores, es bastante probable que en algún momento no se trabaje con la mejor comunicación. Quizá esto ocasione que algún miembro del equipo no logre entregar a tiempo su asignación, no sepa con claridad lo que realmente debe hacer o deduzca que no tiene algún tipo de tarea asignada. Todo esto afectará la entrega oportuna de la solución. 
•	**Recursos del proyecto:** Si en algún momento el alcance del proyecto cambia podría verse afectado el recurso humano o los recursos de software y hardware con los que cuenta el equipo, mayormente recursos como la internet y la disponibilidad de tiempo podrían jugar un papel importante.

**Comment by SarayGal** [comment]
•	Posible interrupción de las operaciones durante el despliegue de la solución.
•	Amenazas externas que violan la seguridad de la aplicación web a través de nuevos métodos.

Considerar los siguientes riesgos
