### ISSUE TITLE
Requisitos de aprobación del proyecto

### ISSUE THREAD

**Issue by Rosmira** [SarayGal/Unac-Virtual-Tracking#8]

**Comment by Rosmira** [comment]
REQUISITOS DE APROBACIÓN DEL PROYECTO (página 8)

Se debe obtener una aprobación general del proyecto mediante reuniones donde se realicen aprobaciones parciales. Para la calificación se evaluarán los entregables teniendo en cuenta el tiempo de entrega y su contenido, esto se realizará en cada una de las etapas del proyecto.


Aprobaciones 

1. Proyecto en documentación revisado 
2. Entregables revisados
3. proyecto final aprobado

**Comment by SarayGal** [comment]
se logrará cuando una solución de la plataforma web completamente probada, y toda la documentación técnica, se implemente por completo en toda la compañía dentro de las limitaciones de tiempo y costo indicadas en este documento. Además, esta medida de éxito debe incluir una lista de recomendaciones para futuras consideraciones de seguridad, ya que anticipamos completamente la necesidad de que esta solución evolucione para prevenir futuras amenazas. El éxito será determinado por el patrocinador del proyecto y del gerente de Proyecto, quien también autorizará la finalización del proyecto.
