### ISSUE TITLE
Entregables del proyecto

### ISSUE THREAD

**Issue by Tecnojack** [SarayGal/Unac-Virtual-Tracking#9]

**Comment by Tecnojack** [comment]
**DECLARACIÓN PRELIMINAR DEL ALCANCE**
Nuestro proyecto incluirá una fase de diseño de la arquitectura solución, posteriormente se realizarán pruebas a la misma y dependiendo del resultado de estas pruebas, estará lista para la entrega la plataforma de gestión de proyecto integrador. Para todas las fases del proyecto, el equipo de desarrollo formado en la clase de Gerencia proyectos informáticos, dispondrá del recurso humano, las máquinas, y los diferentes programas que se requieran para el desarrollo de la solución. El proyecto se realizará durante el primer semestre de 2021 y los desarrolladores trabajarán desde sus casas de manera remota y se hará integración a través de un repositorio en Github.
 
El proyecto será financiado por la corporación universitaria adventista y momentáneamente contamos con que no se realicen modificaciones a lo ya pactado. De haber algún cambio o consideración adicional, el equipo deberá aprobar esta modificación. Este proyecto deberá finalizar para los últimos días del semestre 2021-1. Se deberán realizar las últimas pruebas para el posterior despliegue e implementación de la solución en la corporación universitaria adventista UNAC. Todo esto será posible única y exclusivamente cuando se cuente con toda la documentación técnica completada y el software cumpla con todos los requisitos previamente establecidos mediante decisión unilateral del equipo de desarrollo y su líder técnico.

**Comment by SarayGal** [comment]
Perfección es muy complicado de medir, la puedes omitir
